### ISSUE TITLE
[BUG] Logout/Login Button unclear

### ISSUE THREAD

**Issue by jnaegibbs** [npadilla8/mindful-app#262]
**Describe the bug**
Login/logout buttons are not clear

**To Reproduce**
1. Login
2. Look at navbar

**Expected behavior**
I thought based on appearance that the arrow button would be a "Back" button but it logged me out. No clear logout button.

**Screenshots**
![Screenshot 2023-12-07 at 7 34 11 PM (2)](https://github.com/npadilla8/mindful-app/assets/135480996/5b0d046f-e6b1-4273-bca1-460b194cf44b)

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser: Chrome
 
**Additional context**
N/A

**Comment by npadilla8** [comment]
Added Hover options for all buttons to make it more clear
